### ISSUE TITLE
Somehow causes an error.

### ISSUE THREAD

**Issue by Gynernet** [monkeymanboy/BeatSaberMarkupLanguage#133]
If I have just BSIPA and BSML and no other mods the game crashes with a window named "Beat Saber - Unity 2019.4.28d1_1381962e9d08". I have tried doing all of the recommended fixes for said problem, plus a clean install along with cleaned settings, but none of them have worked.
If I have all mods on mod assistant installed, excluding BSML and any mods that need it, my game runs just fine. If I have no mods the game runs just fine.
I don't know how to gain any more specific info myself, but if I can help you help me then my discord ID is Net-Soul#6284

**Comment by nicoco007** [comment]
Closing this since it's quite old. Feel free to open a new issue if necessary.
