### ISSUE TITLE
Background round-rect-panel no longer takes alpha colour

### ISSUE THREAD

**Issue by qqrz997** [monkeymanboy/BeatSaberMarkupLanguage#147]
not sure if there was a change to the game that caused this, these backgrounds don't change transparency with a hex like `#000000AA`:

in beat saber 1.34.2 (BSML 1.8.1)
![image](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/assets/156676353/37d58e42-db17-4a30-9119-60fb939a9207)

in beat saber 1.36.0 (BSML 1.10.3) - added red colour to test if bg colour is working
![image](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/assets/156676353/dc9e7505-4336-4416-8db6-166cf2ddf54d)

**Comment by nicoco007** [comment]
Oh, this is probably because of [this](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/pull/146/files#diff-fa766ea5d7427774103c283dd7ec2b25e80e2599e166baf77a620a6b123645ecR84). I'll see if I can figure out a way to keep the existing alpha if it's not specified.

**Comment by nicoco007** [comment]
Could you try out [this build](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/actions/runs/8862144842)?

**Comment by qqrz997** [comment]
yes, fixed

![image](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/assets/156676353/0054d193-9f31-4eaa-a5f8-a3773687a871)
