### ISSUE TITLE
docs unclear (causes errors in log

### ISSUE THREAD

**Issue by Futuremappermydud** [monkeymanboy/BeatSaberMarkupLanguage#20]
[_latest.log](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/files/4123811/_latest.log)
[ERROR @ 12:33:41 | BeatSaberMarkupLanguage] Failed to register BSMLViewController

[Plugin.txt](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/files/4123823/Plugin.txt)

**Comment by monkeymanboy** [comment]
Docs are unfinished at the moment they assume you know how to use ViewControllers and FlowCoordinators, for now just look at other mods as an example. Those errors you're getting are from another mod, yours isn't doing anything at the moment.
