### ISSUE TITLE
Ajust spacing of buttons on left menu

### ISSUE THREAD

**Issue by CabbagePenetrator** [monkeymanboy/BeatSaberMarkupLanguage#33]
The mod buttons on the left menu look too close together and should have some space between them.

Here is a picture of before and after changing the space between the buttons:

![Untitled](https://user-images.githubusercontent.com/64737455/81425035-bf3acd80-914e-11ea-8da6-4d9e1f7d2151.jpg)

I've made this change on my fork in this commit 6bcaefe12c9245e5b1bc26a062ed13da58609239

Can I make a PR to merge this change?

**Comment by monkeymanboy** [comment]
Go ahead and make the PR
