### ISSUE TITLE
Crash on startup related to fonts? 

### ISSUE THREAD

**Issue by asteriskchaos** [monkeymanboy/BeatSaberMarkupLanguage#39]
[Crash_2020-07-12_220524665.zip](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/files/4909682/Crash_2020-07-12_220524665.zip)
[_latest.log](https://github.com/monkeymanboy/BeatSaberMarkupLanguage/files/4909684/_latest.log)
I was adding only dependencies to the game to figure out where my problem was, and consistently ran into crashes whenever BSML was added. IPA log ends after trying to fall back on particular fonts, crash log points to access violation by UnityPlayer.dll .

**Comment by nicoco007** [comment]
Closing this since it's very old. Feel free to open a new issue if necessary.
