### ISSUE TITLE
Pure Chinese texts will go upward

### ISSUE THREAD

**Issue by WGzeyu** [monkeymanboy/BeatSaberMarkupLanguage#60]
It seems that only plain Chinese text has this situation. When it contains English or numbers, symbols, it will return to normal
![](https://cdn.discordapp.com/attachments/443146108420620318/769151541633351721/unknown.png)
![](https://cdn.discordapp.com/attachments/443146108420620318/769151562622042122/unknown.png)
![](https://cdn.discordapp.com/attachments/443146108420620318/769151581006331934/unknown.png)

**Comment by nicoco007** [comment]
Closing this since it's very old. I believe this was fixed whenever Beat Saber introduced official translations.
