### ISSUE TITLE
Remove GameplaySetup tabs without requiring a fresh menu scene reload

### ISSUE THREAD

**Issue by Kevga** [monkeymanboy/BeatSaberMarkupLanguage#67]
Referring to this warning: https://github.com/monkeymanboy/BeatSaberMarkupLanguage/blob/d89e2f1e16e72cb9245b73dfb6d7a54f25dcb969/BeatSaberMarkupLanguage/GameplaySetup/GameplaySetup.cs#L43

With the addition of multiplayer there are now mods that only work in singeplayer or only in multiplayer. It would be great if those mods could remove their settings menu from the GameplaySetup in the modes they don't support.

**Comment by monkeymanboy** [comment]
You can specify what menus a gameplay setup view should appear in now. https://github.com/monkeymanboy/BeatSaberMarkupLanguage/commit/9a5d937afdab733bc954480e890e62ea3a9a0fc9
