### ISSUE TITLE
Emoji in truncated text fields crash the game

### ISSUE THREAD

**Issue by Kevga** [monkeymanboy/BeatSaberMarkupLanguage#68]
Text fields that contain emoji crash the game if they contain text that is too long to display in its entirety.
Can be reproduced by a `<text>` tag with `overflow-mode='Ellipsis'` and limited size that contains text with at least one emoji and that is long enough to trigger the overflow. The overflow mode doesn't seem to be a requirement for it to happen though, I've also seen it happen in a list view without that attribute.

I'm not sure if this is a BSML issue or a Unity issue, feel free to close if it's the latter.
I reported this issue to monkeymanboy previously, but thought I'd add it here too so it's documented in some way.

**Comment by nicoco007** [comment]
Closing this since it's very old. Feel free to open a new issue if necessary.
